#              file : _config.yml
#              path : $PROJECT/$file
#              repo : docs.imca-cat.org
#              type : configuration
#    repo_https_url : https://github.com/imcacat/docs.imca-cat.org.git
#      repo_ssh_url : git@github.com:imcacat/docs.imca-cat.org.git

#           purpose :
# * Production Jekyll configuration file:
# * `bundle exec jekyll serve`

#       description :
# * This file contains production(default)-specific settings for the overall Jekyll site.

#             notes :
# * Please see `_config.template.yml` for more information.

#            config :
---
title               : docs.imca-cat.org
description         : A place for documents and things.
url                 : "https://docs.imca-cat.org"       # The base URL of your site
baseurl             : ""                                # The subpath of your site, e.g., /blog (they really picked a `sub`-optimal key name here)
host                : 0.0.0.0                           # The IP address to bind Jekyll server
port                : 443                               # The port to use for the Jekyll server

# Language settings
lang               : en-US

# Server and URL configuration
detach             : false                        # If true, Jekyll will detach from the terminal
show_dir_listing   : false                        # If true, show directory listings

# Output settings
permalink          : date                         # Sets the permalink format
paginate_path      : /page:num                    # Pagination path
timezone           : America/Chicago              # Timezone setting for your site

# Output verbosity
quiet              : false                        # If true, suppresses most build output
verbose            : false                        # If true, increases the verbosity of the output

# Theme configuration
theme               : just-the-docs                # Specifies the theme

# Filtering Content
show_drafts         : null
limit_posts         : 0
future              : false
unpublished         : false

# External links in navigation
nav_external_links :
  "imca_cat.org": "https://imca-cat.org"          # Used in a layout... I think?

# Directories
collections_dir     : ./src/collections # Directory where collections are stored
data_dir            : ./_data           # Directory for data files
destination         : ./_site           # Destination folder where the site will be built
includes_dir        : ./_includes       # Directory for include files
layouts_dir         : ./_layouts        # Directory for layouts
source              : ./src             # Source folder

# Plugins (Some plugins may need to be added to the Gemfile)
plugins:
  - jekyll-asciidoc
  - jekyll-include-cache
  - jekyll-feed

markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

# Liquid profiler
# Generate a Liquid rendering profile to help you identify performance bottlenecks.
# profile: BOOL
# --profile
profile: true
liquid:
  error_mode: warn
  # error_mode: strict
  strict_filters: false
  strict_variables: false

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

# Markdown Processors
kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false

# Sass configuration
sass:
  sass_dir: _sass                                 # Directory for Sass stylesheets

# Collections settings
collections:
  posts:
    output: true                                  # Enable output for posts collection
  tests:
    output: true                                  # Enable output for tests collection
    name: Tests                                   # Give the collection a name
    nav_exclude: true                             # Exclude the collection from the navigation (default: false)
    nav_fold: true                                # Fold the collection in the navigation      (default: false)
    search_exclude: true                          # Exclude the collection from the search     (default: false)
  docs:
    output: true                                  # Enable output for docs collection
    permalink: /:path/:title                      # Permalink format for docs

# Security settings
safe                : false                        # If true, disables custom plugins

# Files and directories to include and exclude from the build
# from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
include:
  - .htaccess
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # specific to the theme website:
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
  # theme test code
  - fixtures/

# Files to keep after the site is built
keep_files:
  - ".git"
  - ".svn"
  - ".hg"

# File encoding
encoding            : "utf-8"                      # Character encoding for files

# Further customization and additional settings
# You can add more here based on what you need, such as SEO tags, additional plugins,
# and other Jekyll configurations not currently listed.

# Example for additional SEO optimization:
# seo_tag:
#   type: "website"                                # Type of SEO tag, e.g., "website" or "article"

# Example to enable search engine sitemaps:
# sitemap:
#   enabled: true                                  # Enables sitemap generation
#defaults            : []
# Plugins
#plugins_dir         : _plugins # takes an array of strings and loads plugins in that order
#whitelist           : []

# Theme options
just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    tests:
       # Give the collection a name
       name: Tests
       # Exclude the collection from the navigation
       # Supports true or false (default)
       nav_exclude: true
       # Fold the collection in the navigation
       # Supports true or false (default)
       nav_fold: true  # note: this option is new in v0.4
       # Exclude the collection from the search
       # Supports true or false (default)
       search_exclude: true
       output: false
    docs:
      # Give the collection a name
      name: docs
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Fold the collection in the navigation
      # Supports true or false (default)
      nav_fold: false  # note: this option is new in v0.4
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false
      output: true
 
  mermaid:
    # Version of mermaid library
    # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
    version: assets/js/mermaid.min.js

   # Navigation
  aux_links:
    "IMCA-CAT Website": "https://imca-cat.org"

  # Enable or disable the site search
  # Supports true (default) or false
  search_enabled: true
  search_full_content: true
  
  search:
    # Split pages into sections that can be searched individually
    # Supports 1 - 6, default: 2
    heading_level: 2
    # Maximum amount of previews per search result
    # Default: 3
    previews: 3
    # Maximum amount of words to display before a matched word in the preview
    # Default: 5
    preview_words_before: 5
    # Maximum amount of words to display after a matched word in the preview
    # Default: 10
    preview_words_after: 10
    # Set the search token separator
    # Default: /[\s\-/]+/
    # Example: enable support for hyphenated search words
    tokenizer_separator: /[\s/]+/
    # Display the relative url in search results
    # Supports true (default) or false
    rel_url: true
    # Enable or disable the search button that appears in the bottom right corner of every page
    # Supports true or false (default)
    button: true
    # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
    focus_shortcut_key: 'k'
  
  enable_copy_code_button: true
 
  # Color scheme
  color_scheme: light # available: "dark", "light", "air", "sun", "aqua", "forest", "midnight", "autumn", "dusk"
  # Custom colors
  primary_color: "#0a0a0a"
  #accent_color: "#c7254e"
  accent_color: #285ee7

  callouts:
    warning:
      title: Warning
      color: red
    custom:
      color: pink
      opacity: 0.3

  # Layout
  layouts_dir: _layouts/
  logo: "/assets/images/logos/imca-cat-logo-72ppi-500x500.png"
  footer_content: "Copyright © IMCA-CAT 2024."
 
  # Google Analytics
  analytics:
    provider: "google_gtag"
    google_gtag:
      tracking_id: "G-TQWJCGVZMZ"
...
